# Generated by Django 3.2.21 on 2023-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('shape', models.CharField(max_length=45)),
                ('cake_count', models.IntegerField()),
                ('weight', models.CharField(max_length=45)),
                ('tier', models.IntegerField()),
                ('wishes', models.CharField(blank=True, db_column='Wishes', max_length=45, null=True)),
                ('desciption', models.CharField(blank=True, max_length=45, null=True)),
                ('photo', models.CharField(blank=True, max_length=45, null=True)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('amount', models.CharField(max_length=45)),
                ('total_price', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'theme',
                'managed': False,
            },
        ),
    ]
