# Generated by Django 3.2.21 on 2023-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('cake_name', models.CharField(max_length=45)),
                ('image1', models.CharField(max_length=200)),
                ('image2', models.CharField(blank=True, max_length=200, null=True)),
                ('image3', models.CharField(blank=True, max_length=200, null=True)),
                ('flavour', models.CharField(max_length=45)),
                ('price', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
