# Generated by Django 3.2.21 on 2023-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_holder', models.CharField(max_length=45)),
                ('cvv', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thpayment',
            fields=[
                ('thpayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_holder', models.CharField(max_length=45)),
                ('cvv', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'thpayment',
                'managed': False,
            },
        ),
    ]
