# Generated by Django 3.2.21 on 2023-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=45)),
                ('review', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
    ]
