# Generated by Django 3.2.21 on 2023-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baker',
            fields=[
                ('baker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('phone_no', models.CharField(max_length=45)),
                ('house_name', models.CharField(max_length=45)),
                ('post_office', models.CharField(max_length=45)),
                ('pin_code', models.CharField(max_length=45)),
                ('district', models.CharField(max_length=45)),
                ('liscense', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'baker',
                'managed': False,
            },
        ),
    ]
